import { createFileRoute } from "@tanstack/react-router";
import { SiteLayout, PageHero, CTASection } from "@/components/SiteLayout";
import { Stat } from "@/components/site/Primitives";

export const Route = createFileRoute("/case-studies/novanest")({
  head: () => ({
    meta: [
      { title: "NovaNest Web Dev & SEO Case Study | Hingol Marketing" },
      { name: "description", content: "How Hingol Marketing delivered an ecommerce speed boost of 2.5s and 3X organic revenue growth for NovaNest Home & Living." },
      { property: "og:title", content: "NovaNest Web Dev & SEO Case Study | Hingol Marketing" },
      { property: "og:description", content: "SEO & Web Development case study: 3X organic revenue, 2.5s improved load time and +150% non-brand traffic for NovaNest Home & Living." },
      { property: "og:type", content: "article" },
      { property: "og:url", content: "/case-studies/novanest" },
    ],
    links: [{ rel: "canonical", href: "/case-studies/novanest" }],
  }),
  component: NovaNestPage,
});

function NovaNestPage() {
  return (
    <SiteLayout>
      <PageHero
        eyebrow="Case Study · Web Dev & SEO · UAE · 2024–PRESENT"
        title="NovaNest Home & Living —"
        highlight="3X organic revenue lift via web performance overhaul."
        subtitle="A full speed and SEO transformation that turned NovaNest's premium home decor store into a high-converting, high-visibility search destination."
      />

      <section className="section-y">
        <div className="container-px mx-auto max-w-5xl space-y-12">
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
            <Stat value="3X" label="Organic Revenue" />
            <Stat value="2.5s" label="Improved Load Time" />
            <Stat value="+150%" label="Non-Brand Search Traffic" />
          </div>

          <Block title="Client Overview">
            <p>
              NovaNest is a premium home and living brand in the UAE offering upscale furniture, lighting, and decor through 
              an online storefront. They sought to grow their organic customer base and scale their digital business 
              without relying solely on escalating paid advertising costs.
            </p>
          </Block>

          <Block title="The Challenges">
            <p>
              While NovaNest had curated collections and a loyal local audience, their online store suffered from 
              poor technical performance. Key obstacles included:
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-3">
              <li>Slow page speeds and high bounce rates due to large unoptimized images and bloated legacy JavaScript.</li>
              <li>Weak crawl budget efficiency with hundreds of duplicated pages generated by faceted ecommerce navigation filters.</li>
              <li>Poor rankings for generic non-brand queries like "mid-century dining tables Dubai" or "premium linen rugs UAE."</li>
              <li>A checkout experience that caused friction for mobile shoppers.</li>
            </ul>
          </Block>

          <Block title="Our Digital Strategy">
            <p>
              We executed a combined web development and SEO programme. The focus was on speeding up performance, 
              redesigning key landing pages for higher conversions, and structuring collections to match high-volume 
              commercial search patterns.
            </p>
          </Block>

          <Block title="Execution">
            <ul className="list-disc pl-5 space-y-2">
              <li>Refactored frontend scripts, implementing code-splitting and deferring non-essential assets to shave 2.5 seconds off load times.</li>
              <li>Introduced automatic WebP/AVIF image generation and lazy-loading across all product catalogs.</li>
              <li>Reconstructed the faceted search and filter settings with canonical tags to prevent crawl bloat.</li>
              <li>Created new collection-level hubs focused on interior style themes and searched keywords.</li>
              <li>Optimized the mobile checkout flow to minimize user friction.</li>
            </ul>
          </Block>

          <Block title="Results">
            <ul className="list-disc pl-5 space-y-2">
              <li>3X growth in revenue generated directly from organic channels.</li>
              <li>2.5s improvement in Core Web Vitals Largest Contentful Paint (LCP) time.</li>
              <li>150% increase in non-brand organic search traffic year-over-year.</li>
              <li>Significant reduction in bounce rate on product and collection pages.</li>
              <li>Achieved top ranking positions for highly competitive home decor and furniture search terms in the UAE.</li>
            </ul>
          </Block>

          <Block title="ROI">
            <p>
              By resolving core speed issues and mapping the collection architecture to organic search intent, 
              NovaNest achieved highly profitable, recurring ecommerce sales that diminished their dependency on paid acquisition.
            </p>
          </Block>

          <Block title="Conclusion">
            <p>
              NovaNest is a classic example of how combining technical frontend development with intent-focused SEO 
              can unlock compounding organic revenue for ecommerce brands in the UAE.
            </p>
          </Block>
        </div>
      </section>

      <CTASection
        title="Ready to speed up and scale your ecommerce store?"
        subtitle="Request a comprehensive technical SEO and performance review of your online shop today."
        primary="Request a Free SEO Audit"
      />
    </SiteLayout>
  );
}

function Block({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="font-display text-2xl md:text-3xl font-bold mb-3">{title}</h2>
      <div className="text-muted-foreground leading-relaxed text-base md:text-lg">{children}</div>
    </div>
  );
}
