/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ServicesWebsiteDevelopmentRouteImport } from './routes/services.website-development'
import { Route as ServicesSocialMediaMarketingRouteImport } from './routes/services.social-media-marketing'
import { Route as ServicesSeoRouteImport } from './routes/services.seo'
import { Route as ServicesPpcAdvertisingRouteImport } from './routes/services.ppc-advertising'
import { Route as ServicesAppDevelopmentRouteImport } from './routes/services.app-development'
import { Route as CaseStudiesZetronixRouteImport } from './routes/case-studies.zetronix'
import { Route as CaseStudiesVaultifyFintechRouteImport } from './routes/case-studies.vaultify-fintech'
import { Route as CaseStudiesThePetShopRouteImport } from './routes/case-studies.the-pet-shop'
import { Route as CaseStudiesSaffronKitchenRouteImport } from './routes/case-studies.saffron-kitchen'
import { Route as CaseStudiesPinnaclePropertiesRouteImport } from './routes/case-studies.pinnacle-properties'
import { Route as CaseStudiesNovanestRouteImport } from './routes/case-studies.novanest'
import { Route as CaseStudiesMedlifeClinicsRouteImport } from './routes/case-studies.medlife-clinics'
import { Route as CaseStudiesLumiereHotelGroupRouteImport } from './routes/case-studies.lumiere-hotel-group'
import { Route as BlogTopSeoTrendsDubai2026RouteImport } from './routes/blog.top-seo-trends-dubai-2026'
import { Route as BlogDubaiBusinessNeedsWebsiteDevelopmentSeoRouteImport } from './routes/blog.dubai-business-needs-website-development-seo'
import { Route as BlogAiPoweredSearchChangingSeoRouteImport } from './routes/blog.ai-powered-search-changing-seo'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ServicesWebsiteDevelopmentRoute =
  ServicesWebsiteDevelopmentRouteImport.update({
    id: '/website-development',
    path: '/website-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesSocialMediaMarketingRoute =
  ServicesSocialMediaMarketingRouteImport.update({
    id: '/social-media-marketing',
    path: '/social-media-marketing',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesSeoRoute = ServicesSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesPpcAdvertisingRoute = ServicesPpcAdvertisingRouteImport.update({
  id: '/ppc-advertising',
  path: '/ppc-advertising',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAppDevelopmentRoute = ServicesAppDevelopmentRouteImport.update({
  id: '/app-development',
  path: '/app-development',
  getParentRoute: () => ServicesRoute,
} as any)
const CaseStudiesZetronixRoute = CaseStudiesZetronixRouteImport.update({
  id: '/zetronix',
  path: '/zetronix',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudiesVaultifyFintechRoute =
  CaseStudiesVaultifyFintechRouteImport.update({
    id: '/vaultify-fintech',
    path: '/vaultify-fintech',
    getParentRoute: () => CaseStudiesRoute,
  } as any)
const CaseStudiesThePetShopRoute = CaseStudiesThePetShopRouteImport.update({
  id: '/the-pet-shop',
  path: '/the-pet-shop',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudiesSaffronKitchenRoute =
  CaseStudiesSaffronKitchenRouteImport.update({
    id: '/saffron-kitchen',
    path: '/saffron-kitchen',
    getParentRoute: () => CaseStudiesRoute,
  } as any)
const CaseStudiesPinnaclePropertiesRoute =
  CaseStudiesPinnaclePropertiesRouteImport.update({
    id: '/pinnacle-properties',
    path: '/pinnacle-properties',
    getParentRoute: () => CaseStudiesRoute,
  } as any)
const CaseStudiesNovanestRoute = CaseStudiesNovanestRouteImport.update({
  id: '/novanest',
  path: '/novanest',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudiesMedlifeClinicsRoute =
  CaseStudiesMedlifeClinicsRouteImport.update({
    id: '/medlife-clinics',
    path: '/medlife-clinics',
    getParentRoute: () => CaseStudiesRoute,
  } as any)
const CaseStudiesLumiereHotelGroupRoute =
  CaseStudiesLumiereHotelGroupRouteImport.update({
    id: '/lumiere-hotel-group',
    path: '/lumiere-hotel-group',
    getParentRoute: () => CaseStudiesRoute,
  } as any)
const BlogTopSeoTrendsDubai2026Route =
  BlogTopSeoTrendsDubai2026RouteImport.update({
    id: '/top-seo-trends-dubai-2026',
    path: '/top-seo-trends-dubai-2026',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogDubaiBusinessNeedsWebsiteDevelopmentSeoRoute =
  BlogDubaiBusinessNeedsWebsiteDevelopmentSeoRouteImport.update({
    id: '/dubai-business-needs-website-development-seo',
    path: '/dubai-business-needs-website-development-seo',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogAiPoweredSearchChangingSeoRoute =
  BlogAiPoweredSearchChangingSeoRouteImport.update({
    id: '/ai-powered-search-changing-seo',
    path: '/ai-powered-search-changing-seo',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/ai-powered-search-changing-seo': typeof BlogAiPoweredSearchChangingSeoRoute
  '/blog/dubai-business-needs-website-development-seo': typeof BlogDubaiBusinessNeedsWebsiteDevelopmentSeoRoute
  '/blog/top-seo-trends-dubai-2026': typeof BlogTopSeoTrendsDubai2026Route
  '/case-studies/lumiere-hotel-group': typeof CaseStudiesLumiereHotelGroupRoute
  '/case-studies/medlife-clinics': typeof CaseStudiesMedlifeClinicsRoute
  '/case-studies/novanest': typeof CaseStudiesNovanestRoute
  '/case-studies/pinnacle-properties': typeof CaseStudiesPinnaclePropertiesRoute
  '/case-studies/saffron-kitchen': typeof CaseStudiesSaffronKitchenRoute
  '/case-studies/the-pet-shop': typeof CaseStudiesThePetShopRoute
  '/case-studies/vaultify-fintech': typeof CaseStudiesVaultifyFintechRoute
  '/case-studies/zetronix': typeof CaseStudiesZetronixRoute
  '/services/app-development': typeof ServicesAppDevelopmentRoute
  '/services/ppc-advertising': typeof ServicesPpcAdvertisingRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/social-media-marketing': typeof ServicesSocialMediaMarketingRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/blog/': typeof BlogIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/ai-powered-search-changing-seo': typeof BlogAiPoweredSearchChangingSeoRoute
  '/blog/dubai-business-needs-website-development-seo': typeof BlogDubaiBusinessNeedsWebsiteDevelopmentSeoRoute
  '/blog/top-seo-trends-dubai-2026': typeof BlogTopSeoTrendsDubai2026Route
  '/case-studies/lumiere-hotel-group': typeof CaseStudiesLumiereHotelGroupRoute
  '/case-studies/medlife-clinics': typeof CaseStudiesMedlifeClinicsRoute
  '/case-studies/novanest': typeof CaseStudiesNovanestRoute
  '/case-studies/pinnacle-properties': typeof CaseStudiesPinnaclePropertiesRoute
  '/case-studies/saffron-kitchen': typeof CaseStudiesSaffronKitchenRoute
  '/case-studies/the-pet-shop': typeof CaseStudiesThePetShopRoute
  '/case-studies/vaultify-fintech': typeof CaseStudiesVaultifyFintechRoute
  '/case-studies/zetronix': typeof CaseStudiesZetronixRoute
  '/services/app-development': typeof ServicesAppDevelopmentRoute
  '/services/ppc-advertising': typeof ServicesPpcAdvertisingRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/social-media-marketing': typeof ServicesSocialMediaMarketingRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/blog': typeof BlogIndexRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/ai-powered-search-changing-seo': typeof BlogAiPoweredSearchChangingSeoRoute
  '/blog/dubai-business-needs-website-development-seo': typeof BlogDubaiBusinessNeedsWebsiteDevelopmentSeoRoute
  '/blog/top-seo-trends-dubai-2026': typeof BlogTopSeoTrendsDubai2026Route
  '/case-studies/lumiere-hotel-group': typeof CaseStudiesLumiereHotelGroupRoute
  '/case-studies/medlife-clinics': typeof CaseStudiesMedlifeClinicsRoute
  '/case-studies/novanest': typeof CaseStudiesNovanestRoute
  '/case-studies/pinnacle-properties': typeof CaseStudiesPinnaclePropertiesRoute
  '/case-studies/saffron-kitchen': typeof CaseStudiesSaffronKitchenRoute
  '/case-studies/the-pet-shop': typeof CaseStudiesThePetShopRoute
  '/case-studies/vaultify-fintech': typeof CaseStudiesVaultifyFintechRoute
  '/case-studies/zetronix': typeof CaseStudiesZetronixRoute
  '/services/app-development': typeof ServicesAppDevelopmentRoute
  '/services/ppc-advertising': typeof ServicesPpcAdvertisingRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/social-media-marketing': typeof ServicesSocialMediaMarketingRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/blog/': typeof BlogIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/services'
    | '/sitemap'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/blog/ai-powered-search-changing-seo'
    | '/blog/dubai-business-needs-website-development-seo'
    | '/blog/top-seo-trends-dubai-2026'
    | '/case-studies/lumiere-hotel-group'
    | '/case-studies/medlife-clinics'
    | '/case-studies/novanest'
    | '/case-studies/pinnacle-properties'
    | '/case-studies/saffron-kitchen'
    | '/case-studies/the-pet-shop'
    | '/case-studies/vaultify-fintech'
    | '/case-studies/zetronix'
    | '/services/app-development'
    | '/services/ppc-advertising'
    | '/services/seo'
    | '/services/social-media-marketing'
    | '/services/website-development'
    | '/blog/'
    | '/case-studies/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/sitemap'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/blog/ai-powered-search-changing-seo'
    | '/blog/dubai-business-needs-website-development-seo'
    | '/blog/top-seo-trends-dubai-2026'
    | '/case-studies/lumiere-hotel-group'
    | '/case-studies/medlife-clinics'
    | '/case-studies/novanest'
    | '/case-studies/pinnacle-properties'
    | '/case-studies/saffron-kitchen'
    | '/case-studies/the-pet-shop'
    | '/case-studies/vaultify-fintech'
    | '/case-studies/zetronix'
    | '/services/app-development'
    | '/services/ppc-advertising'
    | '/services/seo'
    | '/services/social-media-marketing'
    | '/services/website-development'
    | '/blog'
    | '/case-studies'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/services'
    | '/sitemap'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/blog/ai-powered-search-changing-seo'
    | '/blog/dubai-business-needs-website-development-seo'
    | '/blog/top-seo-trends-dubai-2026'
    | '/case-studies/lumiere-hotel-group'
    | '/case-studies/medlife-clinics'
    | '/case-studies/novanest'
    | '/case-studies/pinnacle-properties'
    | '/case-studies/saffron-kitchen'
    | '/case-studies/the-pet-shop'
    | '/case-studies/vaultify-fintech'
    | '/case-studies/zetronix'
    | '/services/app-development'
    | '/services/ppc-advertising'
    | '/services/seo'
    | '/services/social-media-marketing'
    | '/services/website-development'
    | '/blog/'
    | '/case-studies/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRouteWithChildren
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/services/website-development': {
      id: '/services/website-development'
      path: '/website-development'
      fullPath: '/services/website-development'
      preLoaderRoute: typeof ServicesWebsiteDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/social-media-marketing': {
      id: '/services/social-media-marketing'
      path: '/social-media-marketing'
      fullPath: '/services/social-media-marketing'
      preLoaderRoute: typeof ServicesSocialMediaMarketingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/seo': {
      id: '/services/seo'
      path: '/seo'
      fullPath: '/services/seo'
      preLoaderRoute: typeof ServicesSeoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ppc-advertising': {
      id: '/services/ppc-advertising'
      path: '/ppc-advertising'
      fullPath: '/services/ppc-advertising'
      preLoaderRoute: typeof ServicesPpcAdvertisingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/app-development': {
      id: '/services/app-development'
      path: '/app-development'
      fullPath: '/services/app-development'
      preLoaderRoute: typeof ServicesAppDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/case-studies/zetronix': {
      id: '/case-studies/zetronix'
      path: '/zetronix'
      fullPath: '/case-studies/zetronix'
      preLoaderRoute: typeof CaseStudiesZetronixRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/vaultify-fintech': {
      id: '/case-studies/vaultify-fintech'
      path: '/vaultify-fintech'
      fullPath: '/case-studies/vaultify-fintech'
      preLoaderRoute: typeof CaseStudiesVaultifyFintechRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/the-pet-shop': {
      id: '/case-studies/the-pet-shop'
      path: '/the-pet-shop'
      fullPath: '/case-studies/the-pet-shop'
      preLoaderRoute: typeof CaseStudiesThePetShopRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/saffron-kitchen': {
      id: '/case-studies/saffron-kitchen'
      path: '/saffron-kitchen'
      fullPath: '/case-studies/saffron-kitchen'
      preLoaderRoute: typeof CaseStudiesSaffronKitchenRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/pinnacle-properties': {
      id: '/case-studies/pinnacle-properties'
      path: '/pinnacle-properties'
      fullPath: '/case-studies/pinnacle-properties'
      preLoaderRoute: typeof CaseStudiesPinnaclePropertiesRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/novanest': {
      id: '/case-studies/novanest'
      path: '/novanest'
      fullPath: '/case-studies/novanest'
      preLoaderRoute: typeof CaseStudiesNovanestRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/medlife-clinics': {
      id: '/case-studies/medlife-clinics'
      path: '/medlife-clinics'
      fullPath: '/case-studies/medlife-clinics'
      preLoaderRoute: typeof CaseStudiesMedlifeClinicsRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/lumiere-hotel-group': {
      id: '/case-studies/lumiere-hotel-group'
      path: '/lumiere-hotel-group'
      fullPath: '/case-studies/lumiere-hotel-group'
      preLoaderRoute: typeof CaseStudiesLumiereHotelGroupRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/blog/top-seo-trends-dubai-2026': {
      id: '/blog/top-seo-trends-dubai-2026'
      path: '/top-seo-trends-dubai-2026'
      fullPath: '/blog/top-seo-trends-dubai-2026'
      preLoaderRoute: typeof BlogTopSeoTrendsDubai2026RouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/dubai-business-needs-website-development-seo': {
      id: '/blog/dubai-business-needs-website-development-seo'
      path: '/dubai-business-needs-website-development-seo'
      fullPath: '/blog/dubai-business-needs-website-development-seo'
      preLoaderRoute: typeof BlogDubaiBusinessNeedsWebsiteDevelopmentSeoRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/ai-powered-search-changing-seo': {
      id: '/blog/ai-powered-search-changing-seo'
      path: '/ai-powered-search-changing-seo'
      fullPath: '/blog/ai-powered-search-changing-seo'
      preLoaderRoute: typeof BlogAiPoweredSearchChangingSeoRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogAiPoweredSearchChangingSeoRoute: typeof BlogAiPoweredSearchChangingSeoRoute
  BlogDubaiBusinessNeedsWebsiteDevelopmentSeoRoute: typeof BlogDubaiBusinessNeedsWebsiteDevelopmentSeoRoute
  BlogTopSeoTrendsDubai2026Route: typeof BlogTopSeoTrendsDubai2026Route
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogAiPoweredSearchChangingSeoRoute: BlogAiPoweredSearchChangingSeoRoute,
  BlogDubaiBusinessNeedsWebsiteDevelopmentSeoRoute:
    BlogDubaiBusinessNeedsWebsiteDevelopmentSeoRoute,
  BlogTopSeoTrendsDubai2026Route: BlogTopSeoTrendsDubai2026Route,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CaseStudiesRouteChildren {
  CaseStudiesLumiereHotelGroupRoute: typeof CaseStudiesLumiereHotelGroupRoute
  CaseStudiesMedlifeClinicsRoute: typeof CaseStudiesMedlifeClinicsRoute
  CaseStudiesNovanestRoute: typeof CaseStudiesNovanestRoute
  CaseStudiesPinnaclePropertiesRoute: typeof CaseStudiesPinnaclePropertiesRoute
  CaseStudiesSaffronKitchenRoute: typeof CaseStudiesSaffronKitchenRoute
  CaseStudiesThePetShopRoute: typeof CaseStudiesThePetShopRoute
  CaseStudiesVaultifyFintechRoute: typeof CaseStudiesVaultifyFintechRoute
  CaseStudiesZetronixRoute: typeof CaseStudiesZetronixRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesLumiereHotelGroupRoute: CaseStudiesLumiereHotelGroupRoute,
  CaseStudiesMedlifeClinicsRoute: CaseStudiesMedlifeClinicsRoute,
  CaseStudiesNovanestRoute: CaseStudiesNovanestRoute,
  CaseStudiesPinnaclePropertiesRoute: CaseStudiesPinnaclePropertiesRoute,
  CaseStudiesSaffronKitchenRoute: CaseStudiesSaffronKitchenRoute,
  CaseStudiesThePetShopRoute: CaseStudiesThePetShopRoute,
  CaseStudiesVaultifyFintechRoute: CaseStudiesVaultifyFintechRoute,
  CaseStudiesZetronixRoute: CaseStudiesZetronixRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

interface ServicesRouteChildren {
  ServicesAppDevelopmentRoute: typeof ServicesAppDevelopmentRoute
  ServicesPpcAdvertisingRoute: typeof ServicesPpcAdvertisingRoute
  ServicesSeoRoute: typeof ServicesSeoRoute
  ServicesSocialMediaMarketingRoute: typeof ServicesSocialMediaMarketingRoute
  ServicesWebsiteDevelopmentRoute: typeof ServicesWebsiteDevelopmentRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAppDevelopmentRoute: ServicesAppDevelopmentRoute,
  ServicesPpcAdvertisingRoute: ServicesPpcAdvertisingRoute,
  ServicesSeoRoute: ServicesSeoRoute,
  ServicesSocialMediaMarketingRoute: ServicesSocialMediaMarketingRoute,
  ServicesWebsiteDevelopmentRoute: ServicesWebsiteDevelopmentRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRouteWithChildren,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
